package me.suxuan.wardrobe.settings;

import lombok.Getter;
import org.bukkit.inventory.ItemStack;
import org.mineacademy.fo.settings.YamlConfig;

import java.util.List;

// Use to handle buttons setting, including create file, add contents, remove contents...
@Getter
public class ButtonsSetting extends YamlConfig {

	@Getter
	private static final ButtonsSetting instance = new ButtonsSetting();
	private List<ItemStack> buttons;

	private ButtonsSetting() {
		this.setHeader("This file is for buttons config.\nDo not edit this file!");
		this.loadConfiguration(NO_DEFAULT, "menu/buttons.yml");
		this.save();
	}

	@Override
	protected void onLoad() {
		this.buttons = this.getList("Buttons", ItemStack.class);
	}

	@Override
	protected void onSave() {
		this.set("Buttons", this.buttons);
	}

	public void setButtons(List<ItemStack> buttons) {
		this.buttons = buttons;
		this.save();
	}

}
