package me.suxuan.wardrobe.settings;

import lombok.Getter;
import org.bukkit.inventory.ItemStack;
import org.mineacademy.fo.settings.YamlConfig;

import java.util.List;

// Use to handle kit menu setting, including create file, add contents, remove contents...
@Getter
public class KitSetting extends YamlConfig {

	@Getter
	private static final KitSetting instance = new KitSetting();
	private List<ItemStack> menu;

	private KitSetting() {
		this.setHeader("This file is for edit kit menu config.\nDo not edit this file!");
		this.loadConfiguration(NO_DEFAULT, "menu/edit_kit.yml");
		this.save();
	}

	@Override
	protected void onLoad() {
		this.menu = this.getList("Menu", ItemStack.class);
	}

	@Override
	protected void onSave() {
		this.set("Menu", this.menu);
	}

	public void setMenu(List<ItemStack> menu) {
		this.menu = menu;
		this.save();
	}

}
